import { Category, Setting } from "../types/Store_Data";

export const StyleShift_Property_List: { [key: string]: string[] } = {
	Text: ["type", "id", "html", "text_align", "color", "font_size", "Editable"],
	Setting_Sub_Title: ["type", "id", "text", "text_align", "color", "font_size", "Editable"],
	Button: ["type", "id", "description", "icon", "text_align", "color", "font_size", "click_function", "Editable"],
	Checkbox: [
		"type",
		"id",
		"name",
		"description",
		"value",
		"constant_css",
		"setup_function",
		"enable_css",
		"enable_function",
		"disable_css",
		"disable_function",
		"Editable",
	],
	Number_Slide: [
		"type",
		"id",
		"name",
		"description",
		"min",
		"max",
		"step",
		"value",
		"var_css",
		"setup_function",
		"constant_css",
		"update_function",
		"Editable",
	],
	Dropdown: ["type", "id", "name", "description", "value", "constant_css", "setup_function", "options", "Editable"],
	Color: [
		"type",
		"id",
		"name",
		"description",
		"show_alpha_slider",
		"value",
		"var_css",
		"setup_function",
		"constant_css",
		"update_function",
		"Editable",
	],
	Image_Input: ["type", "id", "name", "description", "value", "MaxFileSize", "Editable"],
	Preview_Image: ["type", "id", "Editable"],
	Custom: ["type", "id", "setup_function", "constant_css", "ui_function"],
	Combine_Settings: ["type", "id", "name", "description", "sync_id", "update_function", "Editable"],
};

export const StyleShift_Category_List: Category = { Category: "Category", Selector: "", Rainbow: false, Settings: [] };

export const UI_Preset: Setting[] = [
	{
		type: "Text",
		id: "Test_Text",
		html: "Test Text",
		text_align: "left",
		font_size: 14,
	},
	{
		type: "Setting_Sub_Title",
		id: "Test_Sub_Title",
		text: "Test Setting Sub Title",
		text_align: "left",
		color: "#ffffff",
		font_size: 14,
	},
	{
		type: "Button",
		id: "Test_Button",
		name: "Button",
		description: "",
		icon: "",
		text_align: "center",
		color: "#00FF99",
		font_size: 15,
	},
	{
		type: "Checkbox",
		id: "Test_Checkbox",
		name: "Some Checkbox",
		description: "",
		value: false,
	},
	{
		type: "Number_Slide",
		id: "Test_Number_Slide",
		name: "Just Number Slide",
		description: "",
		min: 0,
		max: 100,
		step: 1,
		value: 50,
	},
	{
		type: "Dropdown",
		id: "Test_Dropdown",
		name: "Just Dropdown",
		description: "",
		value: "Item_1",
		options: { Item_1: {}, Item_2: {}, Item_3: {} },
	},
	{
		type: "Color",
		id: "Test_Color",
		name: "Just Color Selector",
		description: "",
		show_alpha_slider: true,
		value: "#FF0000FF",
	},
	{
		type: "Image_Input",
		id: "Test_Image_Input",
		name: "Just Image Input",
		description: "",
		value: "",
		MaxFileSize: 1000000,
	},
	{
		type: "Preview_Image",
		id: "",
	},
	{
		type: "Custom",
		id: "Test_Custom",
		setup_function: "",
		constant_css: "",
		ui_function: "",
	},
];

export const Type_Convert_Table = {
	function: "js",
	css: "css",
};
